import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { ReactNode } from "react";
import "@/globals.css";

const noto = Noto_Sans({
  weight: "200",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootProps {
  readonly children: ReactNode;
}
export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <body className={`${noto.className} antialiased`}>{children}</body>
    </html>
  );
}
